import { OfficeAgent } from '../types/office';
import type { AgentCode } from '../types/office';

export const OFFICE_ROOM_CONFIG = {
  width: 26,
  depth: 22,
  wallHeight: 9.0,
  floorColor: '#12141c',
  wallColor: '#14141a',
  accentColor: '#D4FF00',
};

/** Active client brand — will be swapped per-client when Portal is connected */
export const CLIENT_BRAND_CONFIG = {
  name: 'Bardinh Coffee & Tea',
  tagline: 'Coffee In Sunset',
  /** Brown brand color from the Bardinh logo */
  primaryColor: '#8B5E3C',
  accentColor: '#C49A6C',
  logoUrl: null as string | null,
};

export interface GardenStationLayout {
  position: [number, number, number];
  rotation: [number, number, number];
  scale: number;
  monitorCount: 2 | 3;
}

/** Authored overview composition for the cinematic garden-office diorama. */
export const GARDEN_STATION_LAYOUT: Record<AgentCode, GardenStationLayout> = {
  A01: { position: [0, 0, 0.85], rotation: [0, 0, 0], scale: 1.05, monitorCount: 3 },
  B02: { position: [-5.45, 0, -3.65], rotation: [0, 0, 0], scale: 0.91, monitorCount: 2 },
  B03: { position: [5.45, 0, -3.65], rotation: [0, 0, 0], scale: 0.91, monitorCount: 2 },
  D01: { position: [-5.65, 0, 2.75], rotation: [0, 0, 0], scale: 0.94, monitorCount: 3 },
  D02: { position: [0, 0, 5.15], rotation: [0, 0, 0], scale: 0.96, monitorCount: 3 },
  E01: { position: [5.65, 0, 2.75], rotation: [0, 0, 0], scale: 0.94, monitorCount: 2 },
};

export const INITIAL_OFFICE_AGENTS: Record<string, OfficeAgent> = {
  A01: {
    code: 'A01',
    displayName: 'A01 — Orchestrator',
    role: 'Trưởng phòng Điều phối Chiến dịch',
    fullDesc: 'Quản trị luồng công việc marketing, phân bổ tác vụ cho các Agent chuyên môn và liên kết với CEO quán.',
    zoneName: 'Khu 1: Điều phối Trung tâm',
    position: [0, 0, -5.0],
    rotation: [0, 0, 0],
    visualState: 'working',
    emotion: 'focused',
    tokenStats: {
      model: 'Claude 3.5 Sonnet',
      tier: 'PRODUCTION',
      budgetUSD: 30,
      totalTokensUsed: 184500,
      maxTokenQuota: 500000,
      tokensIn: 74000,
      tokensOut: 110500,
      remainingPercent: 63,
      usedPercent: 37,
    },
    currentTask: {
      id: 'task-a01-1',
      title: 'Điều phối Chu kỳ Content Tuần 34',
      summary: 'Đang tổng hợp định hướng từ B02 & B03 để kích hoạt D01 viết bài và D02 thiết kế ảnh.',
      time: 'Đang diễn ra',
    },
    recentTasks: [
      { id: 't1', title: 'Khởi tạo chu kỳ lập kế hoạch tuần 34', status: 'done', completedAt: '09:15', category: 'Điều phối' },
      { id: 't2', title: 'Kiểm tra ngân sách token và phân quyền Agent', status: 'done', completedAt: '09:00', category: 'Hệ thống' },
      { id: 't3', title: 'Phân tích phản hồi của khách hàng từ tuần 33', status: 'done', completedAt: 'Hôm qua', category: 'Báo cáo' },
    ],
    requiresHumanAction: false,
    actionPrompt: 'A01 đang vận hành trơn tru quy trình marketing của quán.',
    ctaText: 'Xem Bảng Tổng Quan Tuần',
    ctaHref: '/content-hub',
    updatedAt: 'Vừa xong',
  },
  B02: {
    code: 'B02',
    displayName: 'B02 — Content Pillar',
    role: 'Chuyên gia Trụ cột Nội dung',
    fullDesc: 'Phân tích chân dung khách hàng F&B, định hình 3-4 trụ cột nội dung cốt lõi và các góc tiếp cận món mới.',
    zoneName: 'Khu 2: Chiến lược Nội dung',
    position: [-7.0, 0, -4.5],
    rotation: [0, Math.PI + 0.35, 0],
    visualState: 'idle',
    emotion: 'thinking',
    tokenStats: {
      model: 'Claude 3.5 Sonnet',
      tier: 'STRATEGY',
      budgetUSD: 20,
      totalTokensUsed: 92400,
      maxTokenQuota: 350000,
      tokensIn: 38000,
      tokensOut: 54400,
      remainingPercent: 74,
      usedPercent: 26,
    },
    currentTask: {
      id: 'task-b02-1',
      title: 'Nghiên cứu góc tiếp cận Món mới (Trà Ổi Hồng)',
      summary: 'Xác định thông điệp "Thanh mát giải nhiệt hè" và góc nhìn trải nghiệm tại quán.',
      time: 'Vừa hoàn thiện',
    },
    recentTasks: [
      { id: 't4', title: 'Xây dựng 4 trụ cột content tháng 8', status: 'done', completedAt: '10:30', category: 'Pillar' },
      { id: 't5', title: 'Phân tích đối thủ F&B khu vực lân cận', status: 'done', completedAt: '08:45', category: 'Insight' },
    ],
    requiresHumanAction: false,
    ctaText: 'Xem Định hướng Content',
    ctaHref: '/content-hub',
    updatedAt: '5 phút trước',
  },
  B03: {
    code: 'B03',
    displayName: 'B03 — Content Plan',
    role: 'Chuyên viên Lịch xuất bản',
    fullDesc: 'Lên lịch trình đăng bài tối ưu theo khung giờ vàng tương tác, cân đối tỷ lệ bài bán hàng và bài tương tác.',
    zoneName: 'Khu 2: Chiến lược Nội dung',
    position: [-7.0, 0, 0.5],
    rotation: [0, Math.PI + 0.35, 0],
    visualState: 'idle',
    emotion: 'neutral',
    tokenStats: {
      model: 'GPT-4o Mini',
      tier: 'FAST',
      budgetUSD: 15,
      totalTokensUsed: 68100,
      maxTokenQuota: 300000,
      tokensIn: 27000,
      tokensOut: 41100,
      remainingPercent: 77,
      usedPercent: 23,
    },
    currentTask: {
      id: 'task-b03-1',
      title: 'Xếp lịch xuất bản 7 ngày tới theo ma trận giờ vàng',
      summary: 'Khung 11h30 (Combo trưa) và 19h30 (Không gian chill tối).',
      time: 'Sẵn sàng',
    },
    recentTasks: [
      { id: 't6', title: 'Phân bổ 7 bài viết vào các ngày trong tuần', status: 'done', completedAt: '11:00', category: 'Timeline' },
      { id: 't7', title: 'Gắn thẻ danh mục cho từng ngày', status: 'done', completedAt: '09:20', category: 'Lập lịch' },
    ],
    requiresHumanAction: false,
    ctaText: 'Xem Lịch xuất bản',
    ctaHref: '/content-hub',
    updatedAt: '12 phút trước',
  },
  D01: {
    code: 'D01',
    displayName: 'D01 — Caption Writer',
    role: 'Copywriter Sáng tạo',
    fullDesc: 'Viết lời quảng cáo, câu chuyện thương hiệu và caption bài viết chuẩn phong cách ngôn ngữ F&B của quán.',
    zoneName: 'Khu 3: Sản xuất Sáng tạo',
    position: [7.0, 0, -4.5],
    rotation: [0, Math.PI - 0.35, 0],
    visualState: 'working',
    emotion: 'focused',
    tokenStats: {
      model: 'Claude 3.5 Sonnet',
      tier: 'CREATIVE',
      budgetUSD: 25,
      totalTokensUsed: 215600,
      maxTokenQuota: 450000,
      tokensIn: 86000,
      tokensOut: 129600,
      remainingPercent: 52,
      usedPercent: 48,
    },
    currentTask: {
      id: 'task-d01-1',
      title: 'Viết Caption Bài giới thiệu Combo Trưa',
      summary: 'Hoàn thiện 3 biến thể Hook bắt tai kèm khuyến mãi giảm 20% khung 11h-13h.',
      time: 'Đang viết (65%)',
    },
    recentTasks: [
      { id: 't8', title: 'Viết bài Story Trà Ổi Hồng thanh mát', status: 'done', completedAt: '10:15', category: 'Caption' },
      { id: 't9', title: 'Viết bài Minigame Tặng Voucher Cuối Tuần', status: 'done', completedAt: 'Hôm qua', category: 'Engagement' },
      { id: 't10', title: 'Tối ưu hashtag F&B địa phương', status: 'done', completedAt: 'Hôm qua', category: 'SEO' },
    ],
    requiresHumanAction: false,
    ctaText: 'Xem Bài viết trong Content Hub',
    ctaHref: '/content-hub',
    updatedAt: '2 phút trước',
  },
  D02: {
    code: 'D02',
    displayName: 'D02 — Image Design',
    role: 'Thiết kế Hình ảnh & Visual',
    fullDesc: 'Tạo banner khuyến mãi, ảnh poster món nước và visual bài post đúng tỷ lệ Facebook/Instagram.',
    zoneName: 'Khu 3: Sản xuất Sáng tạo',
    position: [7.0, 0, 0.5],
    rotation: [0, Math.PI - 0.35, 0],
    visualState: 'waiting_human',
    emotion: 'urgent',
    tokenStats: {
      model: 'Qwen 2.5 72B / Imagen',
      tier: 'VISUAL AI',
      budgetUSD: 35,
      totalTokensUsed: 298000,
      maxTokenQuota: 600000,
      tokensIn: 112000,
      tokensOut: 186000,
      remainingPercent: 50,
      usedPercent: 50,
    },
    currentTask: {
      id: 'task-d02-1',
      title: 'Tạo ảnh Banner Khuyến Mãi Cuối Tuần (1080x1080)',
      summary: 'Đang chờ CEO cung cấp ảnh chụp thực tế ly nước để ghép khung thiết kế thương hiệu.',
      time: 'Đang đợi bạn',
    },
    recentTasks: [
      { id: 't11', title: 'Tạo layout poster Món Mới Tháng 8', status: 'done', completedAt: '09:40', category: 'Banner' },
      { id: 't12', title: 'Xuất template story 9:16 Instagram', status: 'done', completedAt: 'Hôm qua', category: 'Story' },
    ],
    requiresHumanAction: true,
    actionPrompt: 'D02 cần bạn tải lên ảnh chụp thực tế món nước để hoàn thiện thiết kế banner.',
    ctaText: 'Tải ảnh món lên Kho media',
    ctaHref: '/assets',
    updatedAt: '1 phút trước',
  },
  E01: {
    code: 'E01',
    displayName: 'E01 — Evaluator',
    role: 'Kiểm duyệt Chất lượng & Tiêu chuẩn',
    fullDesc: 'Chấm điểm chất lượng bài viết theo 5 tiêu chí: Brand Voice, Quy chuẩn F&B, Chính tả, Hook, Call-to-Action.',
    zoneName: 'Khu 4: Kiểm soát Chất lượng',
    position: [0, 0, 5.5],
    rotation: [0, Math.PI, 0],
    visualState: 'reviewing',
    emotion: 'focused',
    tokenStats: {
      model: 'Claude 3.5 Sonnet',
      tier: 'STRICT QA',
      budgetUSD: 20,
      totalTokensUsed: 118200,
      maxTokenQuota: 400000,
      tokensIn: 52000,
      tokensOut: 66200,
      remainingPercent: 70,
      usedPercent: 30,
    },
    currentTask: {
      id: 'task-e01-1',
      title: 'Đánh giá Tiêu chuẩn Bài viết D01 (Combo Trưa)',
      summary: 'Chấm điểm đạt 92/100: Giọng điệu chuẩn, Call-to-Action rõ ràng, không lỗi chính tả.',
      time: 'Đang thẩm định',
    },
    recentTasks: [
      { id: 't13', title: 'Thẩm định bài Story Trà Ổi Hồng (Pass 95/100)', status: 'done', completedAt: '10:20', category: 'Phê duyệt' },
      { id: 't14', title: 'Từ chối bài Minigame do thiếu thời hạn (Rework)', status: 'done', completedAt: 'Hôm qua', category: 'Kiểm duyệt' },
    ],
    requiresHumanAction: false,
    ctaText: 'Xem Bảng Phê duyệt',
    ctaHref: '/approvals',
    updatedAt: '3 phút trước',
  },
};
