// ─── SPEC-0003: Mock Data — Bardinh Coffee, Tuần 25 (16–22/06/2026) ──────────
// Dữ liệu mẫu tương tác cho toàn bộ Client Portal MVP

import {
  Agent,
  TaskCard,
  ContentItem,
  ContentPillar,
  AppNotification,
  MediaAsset,
  AssetRequest,
  BrandVoiceConfig,
  AgentModelConfig,
} from './types';

// ─── Agents ─────────────────────────────────────────────────────────────────
export const AGENTS: Agent[] = [
  {
    code: 'A01',
    name: 'A01 Orchestrator',
    desk: 'strategy',
    icon: '🧠',
    description: 'Điều phối toàn bộ pipeline AI, giao việc cho 5 agent còn lại',
  },
  {
    code: 'B02',
    name: 'B02 Content Pillar',
    desk: 'strategy',
    icon: '🧭',
    description: 'Phân tích thương hiệu, đề xuất Trụ nội dung & Góc khai thác tuần',
  },
  {
    code: 'B03',
    name: 'B03 Content Plan',
    desk: 'strategy',
    icon: '📅',
    description: 'Lên lịch đăng bài tuần, phân bổ platform và khung giờ vàng',
  },
  {
    code: 'D01',
    name: 'D01 Caption Writer',
    desk: 'creative',
    icon: '✍️',
    description: 'Viết caption theo đúng tông giọng thương hiệu và từng platform',
  },
  {
    code: 'D02',
    name: 'D02 Image Designer',
    desk: 'creative',
    icon: '🎨',
    description: 'Tìm ảnh phù hợp, xin ảnh thật từ chủ quán nếu cần',
  },
  {
    code: 'E01',
    name: 'E01 Evaluator',
    desk: 'qa',
    icon: '✅',
    description: 'Chấm điểm tổng hợp nội dung trước khi trình khách duyệt',
  },
];

// ─── Content Pillars — Bardinh Coffee Tuần 25 ───────────────────────────────
export const INITIAL_PILLARS: ContentPillar[] = [
  {
    id: 'p01',
    label: 'Product Spotlight',
    emoji: '☕',
    description: 'Giới thiệu đồ uống, combo, món mới',
    percentage: 40,
    fbRatio: 60,
    igRatio: 40,
    angles: [
      { id: 'a01', label: 'Hương vị đặc trưng' },
      { id: 'a02', label: 'Ảnh flat lay' },
      { id: 'a03', label: 'Video rót đồ uống' },
    ],
  },
  {
    id: 'p02',
    label: 'Behind the Scenes',
    emoji: '🎬',
    description: 'Hậu trường pha chế, barista, không gian quán',
    percentage: 30,
    fbRatio: 40,
    igRatio: 60,
    angles: [
      { id: 'a04', label: 'Barista đang làm việc' },
      { id: 'a05', label: 'Không gian buổi sáng' },
      { id: 'a06', label: 'Nguyên liệu tươi' },
    ],
  },
  {
    id: 'p03',
    label: 'Lifestyle & Cảm xúc',
    emoji: '🌟',
    description: 'Khoảnh khắc tận hưởng, cảm xúc khách hàng',
    percentage: 20,
    fbRatio: 50,
    igRatio: 50,
    angles: [
      { id: 'a07', label: 'Sáng sớm cùng cà phê' },
      { id: 'a08', label: 'Làm việc tại quán' },
    ],
  },
  {
    id: 'p04',
    label: 'Ưu đãi & Sự kiện',
    emoji: '🎁',
    description: 'Khuyến mãi, combo giờ vàng, sự kiện đặc biệt',
    percentage: 10,
    fbRatio: 70,
    igRatio: 30,
    angles: [
      { id: 'a09', label: 'Happy hour' },
      { id: 'a10', label: 'Combo cuối tuần' },
    ],
  },
];

// ─── Content Items — 6 bài viết tuần 25 ─────────────────────────────────────
export const CONTENT_ITEMS: ContentItem[] = [
  {
    id: 'ci-001',
    title: 'Cold Brew Mùa Hè',
    platform: 'ig',
    caption:
      '☀️ Hè về, Bardinh Coffee ra mắt Cold Brew Mùa Hè — Pha lạnh 24 giờ, từng giọt đậm đà như một buổi chiều tà thư giãn.\n\nThưởng thức tại quán hoặc mang về nhé bạn! 🧊✨\n\n#BardinhCoffee #ColdBrew #CaPheDaNong',
    imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
    publishTime: new Date('2026-06-17T08:00:00'),
    state: 'pending_content_approval',
    pillarId: 'p01',
    weekNumber: 25,
    needsRealPhoto: false,
    assetRequestId: null,
  },
  {
    id: 'ci-002',
    title: 'Bạc Xỉu Kem Trứng',
    platform: 'fb',
    caption:
      '🥚✨ Bạc Xỉu Kem Trứng — sự kết hợp hoàn hảo giữa vị cà phê đậm đà và lớp kem trứng béo mịn!\n\nMón mới của Bardinh Coffee đang chờ bạn khám phá. Ghé quán thử nhé?\n📍 Bardin Coffee — 123 Đinh Tiên Hoàng, Q.Bình Thạnh\n\n#BardinhCoffee #BacXiuKemTrung #CaPheSaiGon',
    imageUrl: null,
    publishTime: new Date('2026-06-18T18:00:00'),
    state: 'waiting_asset',
    pillarId: 'p01',
    weekNumber: 25,
    needsRealPhoto: true,
    assetRequestId: 'ar-001',
  },
  {
    id: 'ci-003',
    title: 'Hậu trường barista sáng sớm',
    platform: 'ig',
    caption:
      '⏰ 5:30 sáng tại Bardinh Coffee — Khi cả thành phố còn đang ngủ, barista của chúng mình đã bắt đầu pha mẻ cà phê đầu tiên.\n\nMỗi ly cà phê là cả một quy trình, không chỉ là một thức uống.\n\n#BardinhCoffee #BehindTheScenes #BaristaLife',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
    publishTime: new Date('2026-06-19T17:00:00'),
    state: 'approved_ready_to_post',
    pillarId: 'p02',
    weekNumber: 25,
    needsRealPhoto: false,
    assetRequestId: null,
  },
  {
    id: 'ci-004',
    title: 'Combo Ăn Sáng Bánh Mì',
    platform: 'fb',
    caption:
      '🥖☕ Bắt đầu ngày mới với Combo Ăn Sáng đặc biệt của Bardinh!\n\nBánh mì pate thơm giòn + Cà phê sữa đá mát lạnh = Buổi sáng hoàn hảo 💪\n\nChỉ 55.000đ/combo — Áp dụng 6:00–9:00 sáng hàng ngày!\n\n#BardinhCoffee #AnSangBanhMi #ComboGioVang',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800',
    publishTime: new Date('2026-06-20T18:00:00'),
    state: 'eval_failed',
    pillarId: 'p04',
    weekNumber: 25,
    needsRealPhoto: false,
    assetRequestId: null,
  },
  {
    id: 'ci-005',
    title: 'Không gian làm việc tại quán',
    platform: 'ig',
    caption:
      '💻☕ Bardinh Coffee — Nơi lý tưởng để làm việc, học bài hay đơn giản là nhâm nhi ly cà phê và suy nghĩ.\n\nWifi mạnh, không gian thoải mái, tiếng nhạc nhẹ nhàng — bạn cần gì hơn thế?\n\n#BardinhCoffee #WorkFromCafe #CaPheSaiGon',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
    publishTime: new Date('2026-06-21T17:00:00'),
    state: 'posted',
    pillarId: 'p03',
    weekNumber: 25,
    needsRealPhoto: false,
    assetRequestId: null,
  },
  {
    id: 'ci-006',
    title: 'Happy Hour Thứ 6',
    platform: 'both',
    caption:
      '🎉 Happy Hour Thứ 6 tại Bardinh Coffee!\n\nMua 2 tặng 1 tất cả đồ uống từ 15:00 – 18:00 mỗi thứ Sáu.\n\nTag ngay người bạn muốn rủ đến! 👇\n\n#BardinhCoffee #HappyHour #Thu6Vui',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    publishTime: new Date('2026-06-22T17:00:00'),
    state: 'planned',
    pillarId: 'p04',
    weekNumber: 25,
    needsRealPhoto: false,
    assetRequestId: null,
  },
];

// ─── Kanban Task Cards ────────────────────────────────────────────────────────
export const INITIAL_TASKS: TaskCard[] = [
  // ── Strategy Desk ─────────────────────────────────────
  {
    id: 't-001',
    title: 'B02 — Đề xuất Trụ nội dung Tuần 26',
    assigneeType: 'agent',
    assigneeCode: 'B02',
    desk: 'strategy',
    column: 'todo',
    linkedContentItemId: null,
    retryCount: 0,
    hasError: false,
    slaDeadline: new Date('2026-06-24T18:00:00'),
    createdAt: new Date('2026-06-22T09:00:00'),
    startedAt: null,
    completedAt: null,
  },
  {
    id: 't-002',
    title: 'B03 — Lên lịch Content Plan Tuần 25',
    assigneeType: 'agent',
    assigneeCode: 'B03',
    desk: 'strategy',
    column: 'done',
    linkedContentItemId: null,
    retryCount: 0,
    hasError: false,
    slaDeadline: null,
    createdAt: new Date('2026-06-15T08:00:00'),
    startedAt: new Date('2026-06-15T08:05:00'),
    completedAt: new Date('2026-06-15T08:31:00'),
  },
  {
    id: 't-s2',
    title: '👤 Bạn — Xác nhận Trụ nội dung Tuần 25',
    assigneeType: 'human',
    assigneeCode: 'HUMAN',
    desk: 'strategy',
    column: 'done',
    linkedContentItemId: null,
    retryCount: 0,
    hasError: false,
    slaDeadline: null,
    createdAt: new Date('2026-06-15T09:00:00'),
    startedAt: new Date('2026-06-15T09:00:00'),
    completedAt: new Date('2026-06-15T14:30:00'),
  },

  // ── Creative Desk ─────────────────────────────────────
  {
    id: 't-003',
    title: 'D01 — Viết caption "Cold Brew Mùa Hè"',
    assigneeType: 'agent',
    assigneeCode: 'D01',
    desk: 'creative',
    column: 'done',
    linkedContentItemId: 'ci-001',
    retryCount: 0,
    hasError: false,
    slaDeadline: null,
    createdAt: new Date('2026-06-15T15:00:00'),
    startedAt: new Date('2026-06-15T15:01:00'),
    completedAt: new Date('2026-06-15T15:04:00'),
  },
  {
    id: 't-004',
    title: 'D02 — Xử lý ảnh "Cold Brew Mùa Hè"',
    assigneeType: 'agent',
    assigneeCode: 'D02',
    desk: 'creative',
    column: 'done',
    linkedContentItemId: 'ci-001',
    retryCount: 0,
    hasError: false,
    slaDeadline: null,
    createdAt: new Date('2026-06-15T15:05:00'),
    startedAt: new Date('2026-06-15T15:06:00'),
    completedAt: new Date('2026-06-15T15:22:00'),
  },
  {
    id: 't-005',
    title: 'D01 — Viết caption "Bạc Xỉu Kem Trứng"',
    assigneeType: 'agent',
    assigneeCode: 'D01',
    desk: 'creative',
    column: 'done',
    linkedContentItemId: 'ci-002',
    retryCount: 0,
    hasError: false,
    slaDeadline: null,
    createdAt: new Date('2026-06-15T15:25:00'),
    startedAt: new Date('2026-06-15T15:26:00'),
    completedAt: new Date('2026-06-15T15:29:00'),
  },
  {
    id: 't-006',
    title: 'D02 — Xin ảnh thật "Bạc Xỉu Kem Trứng"',
    assigneeType: 'agent',
    assigneeCode: 'D02',
    desk: 'creative',
    column: 'review',
    linkedContentItemId: 'ci-002',
    retryCount: 0,
    hasError: false,
    slaDeadline: new Date('2026-06-20T23:59:00'),
    createdAt: new Date('2026-06-15T15:30:00'),
    startedAt: new Date('2026-06-15T15:31:00'),
    completedAt: null,
  },
  {
    id: 't-007',
    title: 'D01 — Viết lại caption "Combo Ăn Sáng"',
    assigneeType: 'agent',
    assigneeCode: 'D01',
    desk: 'creative',
    column: 'in_progress',
    linkedContentItemId: 'ci-004',
    retryCount: 1,
    hasError: false,
    slaDeadline: null,
    createdAt: new Date('2026-06-17T10:00:00'),
    startedAt: new Date('2026-06-17T10:05:00'),
    completedAt: null,
  },

  // ── QA Desk ───────────────────────────────────────────
  {
    id: 't-008',
    title: 'E01 — Thẩm định "Cold Brew Mùa Hè"',
    assigneeType: 'agent',
    assigneeCode: 'E01',
    desk: 'qa',
    column: 'done',
    linkedContentItemId: 'ci-001',
    retryCount: 0,
    hasError: false,
    slaDeadline: null,
    createdAt: new Date('2026-06-15T15:23:00'),
    startedAt: new Date('2026-06-15T15:24:00'),
    completedAt: new Date('2026-06-15T15:27:00'),
  },
  {
    id: 't-009',
    title: '👤 Bạn — Duyệt bài "Cold Brew Mùa Hè"',
    assigneeType: 'human',
    assigneeCode: 'HUMAN',
    desk: 'qa',
    column: 'review',
    linkedContentItemId: 'ci-001',
    retryCount: 0,
    hasError: false,
    slaDeadline: new Date('2026-06-19T12:00:00'),
    createdAt: new Date('2026-06-15T15:28:00'),
    startedAt: new Date('2026-06-15T15:28:00'),
    completedAt: null,
  },
  {
    id: 't-010',
    title: 'E01 — Thẩm định "Combo Ăn Sáng" (lần 2)',
    assigneeType: 'agent',
    assigneeCode: 'E01',
    desk: 'qa',
    column: 'todo',
    linkedContentItemId: 'ci-004',
    retryCount: 1,
    hasError: false,
    slaDeadline: null,
    createdAt: new Date('2026-06-17T10:00:00'),
    startedAt: null,
    completedAt: null,
  },
];

// ─── Notifications ───────────────────────────────────────────────────────────
export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n-001',
    type: 'content_ready_for_approval',
    title: 'Bài viết chờ duyệt 🎉',
    body: '"Cold Brew Mùa Hè" đã được E01 thẩm định đạt chuẩn. Bạn có 18 giờ để duyệt!',
    read: false,
    createdAt: new Date('2026-06-15T15:28:00'),
    actionUrl: '/kanban',
    linkedContentItemId: 'ci-001',
  },
  {
    id: 'n-002',
    type: 'asset_request_created',
    title: 'AI cần ảnh thật từ bạn 📸',
    body: 'D02 đang cần 3 ảnh chụp ly Bạc Xỉu Kem Trứng để hoàn thiện bài. Deadline: 20/06.',
    read: false,
    createdAt: new Date('2026-06-15T15:31:00'),
    actionUrl: '/assets',
    linkedContentItemId: 'ci-002',
  },
  {
    id: 'n-003',
    type: 'system',
    title: 'Hậu trường barista đã đăng ✅',
    body: '"Hậu trường barista sáng sớm" đã được đánh dấu đã đăng thành công trên Instagram.',
    read: true,
    createdAt: new Date('2026-06-19T17:05:00'),
    actionUrl: null,
    linkedContentItemId: 'ci-003',
  },
];

// ─── Asset Request (D02 → Bạc Xỉu Kem Trứng) ───────────────────────────────
export const ASSET_REQUESTS: AssetRequest[] = [
  {
    id: 'ar-001',
    contentItemId: 'ci-002',
    shotList: [
      'Chụp ly Bạc Xỉu Kem Trứng từ góc 45° — nền gỗ tối hoặc đá cẩm thạch',
      'Cận cảnh lớp kem trứng đang chảy nhẹ trên mặt ly',
      'Ảnh tổng ly + bánh mì pate — ánh sáng tự nhiên buổi sáng',
    ],
    deadline: new Date('2026-06-20T23:59:00'),
    exampleImageUrl: 'https://images.unsplash.com/photo-1517701604599-bb29b565090b?w=400',
    status: 'pending',
    submittedAssetIds: [],
  },
];

// ─── Media Assets ────────────────────────────────────────────────────────────
export const MEDIA_ASSETS: MediaAsset[] = [
  {
    id: 'ma-001',
    url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=200',
    source: 'real_photo',
    tags: ['cold brew', 'đồ uống', 'mùa hè', 'ly cao'],
    uploadedAt: new Date('2026-06-14T10:00:00'),
    usedInItems: ['ci-001'],
    assetRequestId: null,
  },
  {
    id: 'ma-002',
    url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=200',
    source: 'real_photo',
    tags: ['barista', 'pha chế', 'hậu trường', 'buổi sáng'],
    uploadedAt: new Date('2026-06-10T07:00:00'),
    usedInItems: ['ci-003'],
    assetRequestId: null,
  },
  {
    id: 'ma-003',
    url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=200',
    source: 'real_photo',
    tags: ['không gian', 'làm việc', 'cafe', 'laptop'],
    uploadedAt: new Date('2026-06-12T15:00:00'),
    usedInItems: ['ci-005'],
    assetRequestId: null,
  },
  {
    id: 'ma-004',
    url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=200',
    source: 'ai_generated',
    tags: ['happy hour', 'ưu đãi', 'đồ uống'],
    uploadedAt: new Date('2026-06-16T12:00:00'),
    usedInItems: ['ci-006'],
    assetRequestId: null,
  },
  {
    id: 'ma-005',
    url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200',
    source: 'real_photo',
    tags: ['bánh mì', 'combo', 'ăn sáng'],
    uploadedAt: new Date('2026-06-13T08:00:00'),
    usedInItems: ['ci-004'],
    assetRequestId: null,
  },
  {
    id: 'ma-006',
    url: 'https://images.unsplash.com/photo-1517701604599-bb29b565090b?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517701604599-bb29b565090b?w=200',
    source: 'pending_review',
    tags: [],
    uploadedAt: new Date('2026-06-17T16:00:00'),
    usedInItems: [],
    assetRequestId: 'ar-001',
    notes: 'Ảnh kem trứng thử chụp lần 1 — cần chỉnh ánh sáng',
  },
];

// ─── Brand Voice ─────────────────────────────────────────────────────────────
export const BRAND_VOICE: BrandVoiceConfig = {
  tone: 'Thân thiện, gần gũi, trẻ trung nhưng vẫn chuyên nghiệp. Nghe như người bạn đang kể chuyện về ly cà phê yêu thích.',
  personalityKeywords: ['ấm áp', 'tinh tế', 'chân thật', 'đậm đà', 'Sài Gòn'],
  avoidPhrases: ['giá rẻ', 'khuyến mãi khủng', 'cực kỳ', 'siêu phẩm', 'đỉnh của chóp'],
  goodCaptionExample:
    '☕ Buổi sáng Sài Gòn luôn bắt đầu bằng một ly Cà phê sữa đá — đậm đà, mát lạnh, đủ để yêu thương cả ngày dài.',
  badCaptionExample: 'Đừng bỏ lỡ! Khuyến mãi KHỦNG — Mua 2 tặng 1 siêu đỉnh! Chỉ trong hôm nay!!!',
};

// ─── Agent Model Config ───────────────────────────────────────────────────────
export const AGENT_MODEL_CONFIGS: AgentModelConfig[] = [
  { agentCode: 'A01', selectedModel: 'gpt-4o', tier: 'power', budgetUSD: 15 },
  { agentCode: 'B02', selectedModel: 'gpt-4o', tier: 'power', budgetUSD: 10 },
  { agentCode: 'B03', selectedModel: 'gpt-4o-mini', tier: 'standard', budgetUSD: 5 },
  { agentCode: 'D01', selectedModel: 'gpt-4o-mini', tier: 'standard', budgetUSD: 8 },
  { agentCode: 'D02', selectedModel: 'dall-e-3', tier: 'standard', budgetUSD: 12 },
  { agentCode: 'E01', selectedModel: 'gpt-4o-mini', tier: 'standard', budgetUSD: 5 },
];

// ─── Demo AI Events (for pitching trigger) ───────────────────────────────────
export const DEMO_AI_EVENTS: Omit<AppNotification, 'id' | 'createdAt' | 'read'>[] = [
  {
    type: 'content_ready_for_approval',
    title: '✍️ D01 vừa viết xong bài mới!',
    body: '"Bạc Xỉu Kem Trứng" đã được viết caption và E01 thẩm định đạt chuẩn. Chờ bạn duyệt!',
    actionUrl: '/kanban',
    linkedContentItemId: 'ci-002',
  },
  {
    type: 'asset_request_created',
    title: '📸 D02 cần ảnh thật từ bạn!',
    body: 'Để hoàn thiện banner "Happy Hour Thứ 6", AI cần 2 ảnh chụp không gian quán buổi tối. Deadline: 48h.',
    actionUrl: '/assets',
    linkedContentItemId: 'ci-006',
  },
  {
    type: 'strategy_ready_for_approval',
    title: '🧭 B02 đề xuất Trụ nội dung Tuần 26!',
    body: 'Kế hoạch Trụ nội dung Tuần 26 đã sẵn sàng. B02 gợi ý tăng Behind the Scenes lên 35% do engagement tốt.',
    actionUrl: '/content-hub?tab=pillar',
    linkedContentItemId: null,
  },
];
